### ISSUE TITLE
Maximum No. of unique words in context of large corpora

### ISSUE THREAD

**Issue by vincentheddesheimer** [keyATM/keyATM#203]
Hi all,

I have a question with regard to the preparation of the `dfm`.
In the package description you highlight that one should "aim for 7,000 to 10,000 unique words at the maximum“. 

However, I guess that this highly depends on the size of the whole corpus. In my case I am looking at a corpus of nearly 1Mio documents with more than 800,000 unique words. Trimming down this corpus to 7000-10,000  unique words would considerably reduce the complexity of the content of these documents.

Therefore, I wanted to ask why one should aim for max. 10,000 words and how one should deal with the case of such large corpora.

Thank you!

**Comment by Shusei-E** [comment]
Hi @vincentheddesheimer, the package description is just a general comment. As you pointed out, it depends on the size of the whole corpus. Since the frequency of words follows [Zipf's law](https://en.wikipedia.org/wiki/Zipf%27s_law), we usually don't have to keep many terms.

Unlike specially designed LDA models (e.g., [LightLDA](https://github.com/microsoft/LightLDA)), keyATM is not designed for 1M documents. Trimming the number of unique words / Analyzing the subset of the corpus will reduce the estimation speed.
