### ISSUE TITLE
Vignette for parallel_init

### ISSUE THREAD

**Issue by bshor** [keyATM/keyATM#210]
I successfully fit keyATM with the default single thread mode. I'm interested in going to parallel processing, since I have a 16 core CPU and lots of RAM. The help suggests to use future::plan() but I don't see any further documentation or vignettes or help about this. I have used doParallel() and foreach() before, but I know future is a whole new paradigm.

Can I ask for an example to try to work from, specifically with the keyATM example. For example, changing the keyATM base example to go from single to multithreaded.

**Comment by Shusei-E** [comment]
Hi @bshor, thanks for using our package!

The `future` package is excellent, and you can [call `plan()`](https://future.futureverse.org/reference/multisession.html) at the top.

```r
library(keyATM)
library(future)
plan(multisession)
```

Please note that we can parallelize the pre-processing, but not the model fitting.
Since the Gibbs Sampling part of the algorithm is fundamentally sequential, we decided not to approximate it for parallelization.
Instead, we have [the resume feature](https://keyatm.github.io/keyATM/articles/pkgdown_files/Resume.html) to save the intermediate output.

**Comment by Shusei-E** [comment]
Exactly, initializing the model is an internal step to prepare an object for the model fitting. 
When we fit the model, the package does not parallelize the Gibbs Sampling and avoids unnecessary approximation.
