### ISSUE TITLE
Question: Hyperprior for alpha

### ISSUE THREAD

**Issue by schae211** [keyATM/keyATM#212]
I just pasted it as an image, because the formulas were not formatted correctly by GitHub:

<img width="799" alt="image" src="https://github.com/keyATM/keyATM/assets/62442385/43f42452-0d8e-4e63-b852-7fcb12a3e020">

And if that is correct, why did you opt for it?

And thanks again for developing such a nice software package :)

**Comment by Shusei-E** [comment]
Hi @schae211 
Do you want to set the hyperprior for the alpha?

It's set [here](https://github.com/keyATM/keyATM/blob/master/src/keyATM_meta.cpp#L111), but I don't think the choice of hyperparameters will change a result, because we usually have a good amount of data. That's why I didn't prepare an option to change hyperparameters.

**Comment by schae211** [comment]
okay thanks a lot for the answer :)
